

name: Terraform
on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs: 
 terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: provisioning of ec2
      uses: hashicorp/setup-terraform@v1
      
      with:
    # terraform_version: 0.13.0
       cli_config_credentials_token: ${{ secrets.Terraform-token-1 }}
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Terraform Validate
      id: validate
      run: terraform validate
      
    - name: Terraform Plan
      id: plan
      run: terraform plan
      
    - name: Terraform apply
      id: apply
      run: terraform apply
      
      
      
      
      
      
 
